version: '3.9'

services:
  app:
    build:
      context: ./.docker/php-fpm
      ssh: [ 'default' ]
    ports:
      - "${NGINX_PORT}:80"
    env_file:
      - .env
    volumes:
      - ${LARAVEL_APP_LOCATION}/${LARAVEL_APP_NAME}:/laravel-app
      - ./.docker/php-fpm/site.conf:/etc/nginx/nginx.conf
      - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.socks
    working_dir: /laravel-app
    depends_on:
      - mysql
    container_name: ${APP_CONTAINER_NAME}

  mysql:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    container_name: ${MYSQL_CONTAINER_NAME}

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "${RABBITMQ_PORT}:15672"
    container_name: ${RABBITMQ_CONTAINER_NAME}

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
