name: 'Create composer images'

on:
  push:
    branches:
        - main
        - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  create_composer_images:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Build the stack'
        run: docker-compose up -d
